name: Guard Secrets
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1) Block a committed .env (exact filename)
      - name: Block .env file
        run: |
          if git ls-files --error-unmatch .env >/dev/null 2>&1; then
            echo "::error title=.env detected::.env must never be committed."
            exit 1
          fi

      # 2) Scan for obvious secrets
      - name: Scan for obvious secrets
        run: |
          set -e
          bad=$(git grep -nE 'TELEGRAM_BOT_TOKEN=|COINBASE_API_KEY=|COINBASE_API_SECRET=|PASSPHRASE=' || true)
          if [ -n "$bad" ]; then
            echo "::error title=Possible secrets found::$bad"
            exit 1
          fi
